### ISSUE TITLE
Object Input Stream

### ISSUE THREAD

**Issue by JonRodriguez98** [ShaneCupid/CodeDevils#12]
Whenever an object is read from a file it is added to the HashMap. Within the program the hashmap's key is initialized to the Object's contact Id within the Contact class.

![Input](https://user-images.githubusercontent.com/99271789/160019586-3482966a-d292-45c5-a085-dfd595fdf497.jpg)

 Inside this class whenever an object is created the object updates a final integer to add a unique contact ID to every instance created of the Contact class.

![ContactClass](https://user-images.githubusercontent.com/99271789/160019843-dfb86ed6-e5e6-4569-8d2e-96228fd8eb1a.jpg)

The issue with this is whenever we import objects through an input stream. This nextID variable is not being updated within the contact class. Therefor whenever the program is executed again, the nextID is re-initialized to 1, causing the objects that were read into the file to be overridden whenever a new object is created during the new execution.
![Output](https://user-images.githubusercontent.com/99271789/160019284-449d2698-3de1-4934-9dfb-2915f9a26ec5.jpg)

**Comment by NoirPhantom** [comment]
Issue has been solved in current commit.
